-- MySQL Script generated by MySQL Workbench
-- Tue Jul 15 10:44:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alqualis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alqualis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alqualis` DEFAULT CHARACTER SET utf8 ;
USE `alqualis` ;

-- -----------------------------------------------------
-- Table `alqualis`.`produtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alqualis`.`produtor` (
  `id_produtor` INT NOT NULL AUTO_INCREMENT,
  `nome_produtor` VARCHAR(100) NOT NULL,
  `cpf_produtor` VARCHAR(11) NULL,
  `codigo_produtor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_produtor`),
  UNIQUE INDEX `codigo_produtor_UNIQUE` (`id_produtor` ASC) VISIBLE,
  UNIQUE INDEX `cpf_prdutor_UNIQUE` (`cpf_produtor` ASC) VISIBLE,
  UNIQUE INDEX `codigo_produtor_UNIQUE` (`codigo_produtor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alqualis`.`comunidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alqualis`.`comunidade` (
  `id_comunidade` INT NOT NULL AUTO_INCREMENT,
  `nome_comunidade` VARCHAR(100) NULL,
  PRIMARY KEY (`id_comunidade`),
  UNIQUE INDEX `id_comunidade_UNIQUE` (`id_comunidade` ASC) VISIBLE,
  UNIQUE INDEX `nome_comunidade_UNIQUE` (`nome_comunidade` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alqualis`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alqualis`.`municipio` (
  `id_municipio` INT NOT NULL AUTO_INCREMENT,
  `nome_municipio` VARCHAR(100) NULL,
  PRIMARY KEY (`id_municipio`),
  UNIQUE INDEX `id_municipio_UNIQUE` (`id_municipio` ASC) VISIBLE,
  UNIQUE INDEX `nome_municipio_UNIQUE` (`nome_municipio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alqualis`.`cooperativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alqualis`.`cooperativa` (
  `id_cooperativa` INT NOT NULL AUTO_INCREMENT,
  `nome_cooperativa` VARCHAR(100) NULL,
  PRIMARY KEY (`id_cooperativa`),
  UNIQUE INDEX `nome_cooperativa_UNIQUE` (`nome_cooperativa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alqualis`.`variedade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alqualis`.`variedade` (
  `id_variedade` INT NOT NULL AUTO_INCREMENT,
  `nome_variedade` VARCHAR(100) NULL,
  PRIMARY KEY (`id_variedade`),
  UNIQUE INDEX `nome_variedade_UNIQUE` (`nome_variedade` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alqualis`.`plantacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alqualis`.`plantacao` (
  `id_plantacao` INT NOT NULL AUTO_INCREMENT,
  `id_produtor` INT NOT NULL,
  `id_variedade` INT NOT NULL,
  `id_comunidade` INT NOT NULL,
  `id_municipio` INT NOT NULL,
  `nome_plantacao` VARCHAR(100) NOT NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `altitude_media` VARCHAR(45) NULL,
  `nome_talhao` VARCHAR(100) NULL,
  `face_exposicao` VARCHAR(200) NULL,
  `meses_colheita` VARCHAR(200) NULL,
  PRIMARY KEY (`id_plantacao`),
  INDEX `id_produto_idx` (`id_produtor` ASC) VISIBLE,
  INDEX `id_variedade_idx` (`id_variedade` ASC) VISIBLE,
  INDEX `id_comunidade_idx` (`id_comunidade` ASC) VISIBLE,
  INDEX `id_municipio_idx` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `id_produtor`
    FOREIGN KEY (`id_produtor`)
    REFERENCES `alqualis`.`produtor` (`id_produtor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_variedade`
    FOREIGN KEY (`id_variedade`)
    REFERENCES `alqualis`.`variedade` (`id_variedade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_comunidade`
    FOREIGN KEY (`id_comunidade`)
    REFERENCES `alqualis`.`comunidade` (`id_comunidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_municipio`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `alqualis`.`municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alqualis`.`cooperativa_produtor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alqualis`.`cooperativa_produtor` (
  `id_cooperativa_produtor` INT NOT NULL AUTO_INCREMENT,
  `id_cooperativa` INT NOT NULL,
  `id_produtor` INT NOT NULL,
  PRIMARY KEY (`id_cooperativa_produtor`),
  INDEX `id_prdutor_idx` (`id_produtor` ASC) VISIBLE,
  INDEX `id_cooperativa_idx` (`id_cooperativa` ASC) VISIBLE,
  CONSTRAINT `id_cooperativa`
    FOREIGN KEY (`id_cooperativa`)
    REFERENCES `alqualis`.`cooperativa` (`id_cooperativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_prdutor`
    FOREIGN KEY (`id_produtor`)
    REFERENCES `alqualis`.`produtor` (`id_produtor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alqualis`.`face_exposicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alqualis`.`face_exposicao` (
  `id_face_exposicao` INT NOT NULL AUTO_INCREMENT,
  `nome_face_exposicao` VARCHAR(100) NULL,
  PRIMARY KEY (`id_face_exposicao`),
  UNIQUE INDEX `nome_face_exposicao_UNIQUE` (`nome_face_exposicao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alqualis`.`face_exposicao_plantacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alqualis`.`face_exposicao_plantacao` (
  `id_face_exposicao_plantacao` INT NOT NULL AUTO_INCREMENT,
  `id_face_exposicao` INT NULL,
  `id_plantacao` INT NULL,
  PRIMARY KEY (`id_face_exposicao_plantacao`),
  INDEX `id_face_exposicao_idx` (`id_face_exposicao` ASC) VISIBLE,
  INDEX `id_plantacao_idx` (`id_plantacao` ASC) VISIBLE,
  CONSTRAINT `id_face_exposicao`
    FOREIGN KEY (`id_face_exposicao`)
    REFERENCES `alqualis`.`face_exposicao` (`id_face_exposicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_plantacao`
    FOREIGN KEY (`id_plantacao`)
    REFERENCES `alqualis`.`plantacao` (`id_plantacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
